version: "3.9"

services:
  data-collector:
    #build: ./demo-galaxea
    image: ghcr.io/lemongooo/data-collector:latest 
    volumes:
      - ./t-ACT-ROS/dataset:/root/Documents/t-ACT-ROS/dataset
      - ./demo-galaxea:/workspace
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    ipc: host
    shm_size: '16gb'
    ulimits:
      memlock: -1
      stack: 67108864
    # command: /bin/bash
    # command: /isaac-sim/python.sh /workspace/main1.
    # entrypoint: ["/isaac-sim/python.sh", "/workspace/main1.py"]
    entrypoint: ["/isaac-sim/python.sh"]
    command: ["/workspace/main1.py"]

  trainer:
    #build: ./t-ACT-ROS   
    image: ghcr.io/lemongooo/trainer:latest    
    volumes:
      - ./t-ACT-ROS/dataset:/workspace/dataset
      - ./t-ACT-ROS/checkpoints:/workspace/checkpoints
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    ipc: host
    shm_size: '16gb'   
    ulimits:
      memlock: -1
      stack: 67108864
    command: >
      python train.py
        --data_path /workspace/dataset
        --save_dir /workspace/checkpoints
