version: "3.9"

services:
  data-collector:
    container_name: data-collector
    image: ghcr.io/lemongooo/data-collector:latest 
    volumes:
      - ./t-ACT-ROS/dataset:/root/Documents/t-ACT-ROS/dataset
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    ipc: host
    shm_size: '16gb'
    ulimits:
      memlock: -1
      stack: 67108864
    entrypoint: ["/bin/bash", "-c"]
    command: ["/isaac-sim/python.sh -m pip install psutil && /isaac-sim/python.sh /workspace/main1.py"]


  trainer:
    container_name: trainer   
    image: ghcr.io/lemongooo/trainer:latest    
    volumes:
      - ./t-ACT-ROS/dataset:/workspace/dataset
      - ./t-ACT-ROS/checkpoints:/workspace/checkpoints
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    ipc: host
    shm_size: '16gb'   
    ulimits:
      memlock: -1
      stack: 67108864
    command: >
      python train.py
        --data_path /workspace/dataset
        --save_dir /workspace/checkpoints
  
  isaac-node:
    image: isaac-sim-node:test
    container_name: isaac-node
    environment:
      - ACCEPT_EULA=Y
      - ROS_DISTRO=humble
      - RMW_IMPLEMENTATION=rmw_fastrtps_cpp
      - DISPLAY=${DISPLAY}
      - NVIDIA_DRIVER_CAPABILITIES=all
      - NVIDIA_VISIBLE_DEVICES=all
    runtime: nvidia
    network_mode: "host"
    ipc: host
    shm_size: '16gb'
    working_dir: /workspace/inference_ros
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./t-ACT-ROS/usd:/workspace/usd
      - ./t-ACT-ROS/checkpoints:/workspace/checkpoints
      - ./t-ACT-ROS/model:/workspace/model
    # depends_on:
    #   - trainer
    entrypoint: []
    #非常重要！！numpy必须是1.26.0版本，否则会报错
    #请使用python.sh启动脚本，而不是runapp.sh
    command: ["/bin/bash", "-c", "/isaac-sim/python.sh -m pip install numpy==1.26.0 --force-reinstall --no-deps -i https://pypi.tuna.tsinghua.edu.cn/simple && /isaac-sim/python.sh /workspace/inference_ros/isaac_node_single.py"]

  
  model-node:
      image: model-node:test
      container_name: model-node
      environment:
        - ROS_DISTRO=humble
        - RMW_IMPLEMENTATION=rmw_fastrtps_cpp
      runtime: nvidia
      network_mode: "host"
      ipc: host
      shm_size: '16gb'
      working_dir: /workspace/inference_ros
      volumes:
        - ./t-ACT-ROS/model:/workspace/model
        - ./t-ACT-ROS/checkpoints:/workspace/checkpoints
      # depends_on:
      #   - isaac-node
      command: ["/bin/bash", "-c", "source /opt/ros/humble/setup.bash && python3 /workspace/inference_ros/mnode_single.py --device=cuda"]

