apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: checkpoints-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi  # ← 根据 checkpoint 大小调整
  storageClassName: manual  # ← 根据你的集群调整

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: checkpoints-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual  # ← 自定义名称
  hostPath:
    path: /mnt/data/checkpoints  # ← 节点上的路径
    type: DirectoryOrCreate