apiVersion: apps/v1
kind: Deployment
metadata:
  name: isaac-node
spec:
  replicas: 1
  selector:
    matchLabels:
      app: isaac-node
  template:
    metadata:
      labels:
        app: isaac-node
    spec:
      hostNetwork: true
      hostIPC: true
      nodeSelector:
        tier: fog
      runtimeClassName: nvidia
      containers:
      - name: isaac-node
        image: ghcr.io/lemongooo/isaac-sim-node:latest
        workingDir: /workspace/inference_ros
        env:
        - { name: ACCEPT_EULA, value: "Y" }
        - { name: OMNI_KIT_ALLOW_ROOT, value: "1" }
        - { name: DISPLAY, value: ":0" }
        - { name: ROS_DISTRO, value: "humble" }
        - { name: RMW_IMPLEMENTATION, value: "rmw_fastrtps_cpp" }
        - { name: ROS_DOMAIN_ID, value: "0" }
        - { name: ROS_LOCALHOST_ONLY, value: "0" }
        - { name: FASTRTPS_DEFAULT_PROFILES_FILE, value: "/workspace/fastdds.xml" }
        - { name: NVIDIA_DRIVER_CAPABILITIES, value: "all" }
        - { name: NVIDIA_VISIBLE_DEVICES, value: "all" }
        resources:
          requests: { nvidia.com/gpu: "1", memory: "24Gi" }
          limits:   { nvidia.com/gpu: "1", memory: "32Gi" }
        volumeMounts:
        - { name: x11, mountPath: /tmp/.X11-unix }
        - { name: dshm, mountPath: /dev/shm }
        - { name: fastdds, mountPath: /workspace/fastdds.xml}
        command: ["/bin/bash","-lc"]
        args:
        - >
          sleep infinity
      volumes:
      - name: x11
        hostPath: { path: /tmp/.X11-unix, type: Directory }
      - name: dshm
        emptyDir: { medium: Memory, sizeLimit: 16Gi }
      - name: fastdds
        hostPath: { path: /mnt/data/fastdds.xml, type: File }
